title: JustANesta Blog
author: @anesta95
email: adriannesta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Adrian Nesta's blog of data journalism projects. Exploring the data behind everyday sports, politics, economics, and more.
theme: jekyll-theme-minimal
# social links
twitter_username: @justanesta
github_username:  @anesta95

show_excerpts: true # set to false to remove excerpts on the homepage
